/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.co.lycorp.geojson.validator

import jp.co.lycorp.geojson.LineString
import jp.co.lycorp.geojson.Position
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertDoesNotThrow
import org.junit.jupiter.api.assertThrows

class LineStringValidatorTest {
    @Test
    fun `should fail when coordinates size is less than 2`() {
        val lineString = listOf(
            Position(10.0, 0.0),
        )
        val err = assertThrows<IllegalArgumentException> { LineString(lineString) }
        val expected = "LineString coordinates must have at least 2 Positions"
        val actual = err.message
        assertEquals(expected, actual)
    }

    @Test
    fun `should pass validation check when coordinates size is more than 2`() {
        val lineString = listOf(
            Position(10.0, 0.0),
            Position(10.0, 1.0),
        )
        assertDoesNotThrow { LineString(lineString) }
    }
}
