name: Run tests and code checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  # Required by mikepenz/action-junit-report
  checks: write
  # Required by actions/checkout
  contents: read
  # Required by mi-kas/kover-report
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Run test
        run: ./gradlew check --no-daemon
