name: Run tests and code checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  # Required by mikepenz/action-junit-report
  checks: write
  # Required by actions/checkout
  contents: read
  # Required by mi-kas/kover-report
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Run test
        run: ./gradlew check --no-daemon

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-test-results
          path: '**/build/test-results/test/TEST-*.xml'
          retention-days: 1

      - name: Create coverage report
        if: ${{ github.event.pull_request }}
        run: ./gradlew koverXmlReport

      - name: Post coverage report as comment
        if: ${{ github.event.pull_request }}
        uses: mi-kas/kover-report@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            ${{ github.workspace }}/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE

---
name: report
on:
  workflow_run:
    workflows: [ Upload Test Report ]
    types: [ completed ]

permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v10
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/build/test-results/test/TEST-*.xml'
